---
apiVersion: v1
kind: Deployment
metadata:
  name: finance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-app
  template:
    metadata:
      lables: 
        app: finance-app
    spec:
      containers:
      - name: finance-app
        image: mahithareddy/banking-finance:1.0
        ports: 
        - containerport: 8081
        env:
        - name: port
          vakue: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: finance-app-service
  spec:
    selector:
      app: finance-app
    ports:
      - port: 8081
        targetport: 8081
        protocol: TCP
    type: NodePort
    nodePort: 30081
